services:
  db:
    image: postgres:17-alpine
    container_name: todo-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_list_dev
    ports:
      - "5433:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - todo-network-dev

volumes:
  db_data_dev:
    driver: local

networks:
  todo-network-dev:
    driver: bridge
